title: Karang Taruna Dusun Wonolobo
description: Portal resmi Karang Taruna Desa Sejahtera — Pemuda Berkarya, Desa Berjaya.
url: https://greenblog-dev.github.io
baseurl: " "
lang: id-ID
timezone: Asia/Jakarta

# Author & Organization
author: Ahla Wisnu
email: wisnudiary@gmail.com
logo: /assets/img/logo.png

# Social
social:
  facebook: https://facebook.com/yuna.arrr
  instagram: https://instagram.com/awvr.verse
  youtube: https://youtube.com/@ahladogital_ai
  twitter: https://twitter.com/username
  whatsapp: https://wa.me/6285875556123

# Build
markdown: kramdown
highlighter: rouge
permalink: /berita/:year/:month/:day/:title/
paginate: 6
paginate_path: "/berita/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..3

plugins:
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Redaksi Karang Taruna"
      comments: true
  - scope:
      path: "_pages"
    values:
      layout: page

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Giscus
giscus:
  repo: greenblog-dev/greenblog-dev.github.io
  repo_id: "R_kgDOTJonmg"
  category: "Announcements"
  category_id: "DIC_kwDOTJonms4DAQNg"
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 0
  theme: light
  lang: id

# SEO
twitter:
  username: karangtaruna
facebook:
  publisher: https://facebook.com/karangtaruna.sejahtera
